-- This file is automatically generated by Supabase. Do not edit this file manually.
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "name" "text",
    "is_admin" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
    
);

CREATE TABLE IF NOT EXISTS "public"."ccostos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nombre" "text" NOT NULL,
    "codigo" "text" NOT NULL,
    "estado" "public"."estado",
    "fecha_inicio" "date",
    "fecha_termino" "date",
    "user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"()
);

CREATE TABLE IF NOT EXISTS "public"."expenses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nombre" "text",
    "rut_rendidor" "text",
    "motivo" "text",
    "monto" numeric(15,2),
    "rut_emisor" "text",
    "numero_documento" "text",
    "fecha" "date",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "tipo_documento" "text",
    "user_id" "uuid",
    "documentos" "jsonb",
    "abono" numeric(15,2),
    "gasto" numeric(15,2),
    "balance" numeric(15,2),
    "cod_obra" "text",
    "no_rend" "text",
    "rut_receptor" "text",
    "id_rend" integer,
    "archivado" boolean DEFAULT false
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "updated_by" "uuid",
);

CREATE TYPE "public"."estado_rendicion" AS ENUM (
    'Aprobado',
    'Pendiente',
    'Rechazado'
);

